/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekt.zavrsnirad.view;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import projekt.zavrsnirad.controller.ObradaEkipa;
import projekt.zavrsnirad.controller.ObradaIgrac;
import projekt.zavrsnirad.controller.ObradaStatistika;
import projekt.zavrsnirad.controller.ObradaTrener;
import projekt.zavrsnirad.controller.ObradaUtakmica;
import projekt.zavrsnirad.model.Igrac;
import projekt.zavrsnirad.model.Utakmica;

/**
 *
 * @author valagic
 */
public class tablicaIzvjestaji extends javax.swing.JFrame {

    private ObradaEkipa obradaEkipa;
    private ObradaIgrac obradaIgrac;
    private ObradaStatistika obradaStatistika;
    private ObradaTrener obradaTrener;
    private ObradaUtakmica obradaUtakmica;
    SimpleDateFormat sdf;
    DecimalFormatSymbols symbols = new DecimalFormatSymbols(new Locale("hr","HR"));
        DecimalFormat df = new DecimalFormat("###,###.00",symbols);
    
    /**
     * Creates new form tablicaIzvjestaji
     */
    public tablicaIzvjestaji() {
        initComponents();
        obradaEkipa = new ObradaEkipa();
        obradaIgrac = new ObradaIgrac();
        obradaStatistika = new ObradaStatistika();
        obradaTrener = new ObradaTrener();
        obradaUtakmica = new ObradaUtakmica();
        sdf = new SimpleDateFormat("dd.MM.yyyy");
        ucitaj();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUtakmica = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUtakmica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Datum Pocetka", "Naziv Dvorane", "Domaca Ekipa", "Gostujuca Ekipa", "Ime", "Prezime", "Statistika"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUtakmica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUtakmica;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {
        
        List<Utakmica> utakmica = obradaUtakmica.read();
        List<Igrac> igrac = obradaIgrac.read();
        
        
        DefaultTableModel tblModel = (DefaultTableModel)tblUtakmica.getModel();
        
        for(Utakmica m : utakmica){
            String row[] = {
                m.getId().toString(),
                sdf.format(m.getDatumPocetka()).toString(),
                m.getNazivDvorane().toString(),
                m.getDomaca().toString(),
                m.getGost().toString()
            };
            tblModel.addRow(row);
        }
        for(Igrac i : igrac){
            String row[] = {
                i.getIme().toString(),
                i.getPrezime().toString(),
                i.getStatistika().toString()
                    
            };
            tblModel.addRow(row);
        }
        tblUtakmica.repaint();     
    }    
}

